server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://121.40.115.158:3306/cloud-order?useSSL=false
    username: root
    password: Gg13506800412
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.247.50:8848
        cluster-name: HZ
        ephemeral: true
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule #负载均衡规则

ribbon:
  eager-load:
    enabled: true
    clients:
       - userservice
